# ── main.py ────────────────────────────────
import pandas as pd
import os
from scanner.screener import run_screener

# Top 250 NSE stocks — High Volume + High Turnover (verified symbols)
SYMBOLS = [
    # Nifty 50 — Large Cap High Volume
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY",
    "SBIN","HINDUNILVR","ITC","KOTAKBANK","LT",
    "AXISBANK","BAJFINANCE","BHARTIARTL","ASIANPAINT","MARUTI",
    "HCLTECH","SUNPHARMA","WIPRO","ULTRACEMCO","TITAN",
    "NESTLEIND","POWERGRID","NTPC","ONGC","TECHM",
    "BAJAJFINSV","DRREDDY","DIVISLAB","CIPLA","ADANIENT",
    "ADANIPORTS","COALINDIA","BPCL","HEROMOTOCO","EICHERMOT",
    "HINDALCO","TATASTEEL","JSWSTEEL","GRASIM","SHREECEM",
    "INDUSINDBK","TATACONSUM","APOLLOHOSP","BRITANNIA","SBILIFE",
    "HDFCLIFE","BAJAJ-AUTO","M&M","TATAMOTORS","UPL",
    # Nifty Next 50 — High Turnover
    "ADANIGREEN","AMBUJACEM","AUROPHARMA","BANDHANBNK","BERGEPAINT",
    "BIOCON","BOSCHLTD","CANBK","CHOLAFIN","COLPAL",
    "CONCOR","DABUR","DLF","FEDERALBNK","GAIL",
    "GODREJCP","GODREJPROP","HAVELLS","ICICIPRULI","ICICIGI",
    "INDUSTOWER","JINDALSTEL","LUPIN","MARICO","MCDOWELL-N",
    "NAUKRI","NMDC","PAGEIND","PERSISTENT","PETRONET",
    "PIDILITIND","PNB","RECLTD","SAIL","SIEMENS",
    "SRF","TORNTPHARM","TRENT","TVSMOTOR","UBL",
    "VEDL","VOLTAS","YESBANK","ZEEL","ZOMATO",
    "IRCTC","DMART","NYKAA","PAYTM","POLICYBZR",
    # Nifty Midcap 100 — High Volume
    "ABCAPITAL","ABFRL","ALKEM","APLLTD","ASHOKLEY",
    "ASTRAL","AUBANK","BALKRISIND","BATAINDIA","BEL",
    "BHARATFORG","BHEL","CAMS","CANFINHOME","COFORGE",
    "CROMPTON","CUMMINSIND","DEEPAKNTR","ESCORTS","EXIDEIND",
    "FORTIS","GLENMARK","GMRINFRA","GNFC","GRANULES",
    "HAPPSTMNDS","HDFCAMC","IDFCFIRSTB","IEX","INDIAMART",
    "INDIGO","JKCEMENT","JSWENERGY","JUBLFOOD","KAJARIACER",
    "KANSAINER","KEI","KPITTECH","LAURUSLABS","LICI",
    "LTIM","LTTS","LUXIND","MANAPPURAM","MANKIND",
    "MCX","METROPOLIS","MFSL","MOTHERSON","NATCOPHARM",
    "NATIONALUM","NAVINFLUOR","NBCC","NCC","NHPC",
    "NLCINDIA","OFSS","OIL","PHOENIXLTD","POLYCAB",
    "RADICO","RAILTEL","RAMCOCEM","RITES","RBLBANK",
    "SBICARD","SCHAEFFLER","SOBHA","SUNDARMFIN","SUNDRMFAST",
    "SUNTV","SUZLON","SYNGENE","TANLA","TATACHEM",
    "TATACOMM","TATAELXSI","TATAPOWER","TIINDIA","TIMKEN",
    "TORNTPOWER","TTKPRESTIG","UJJIVANSFB","UNIONBANK","UTIAMC",
    "VINATIORGA","WELCORP","WELSPUNIND","ZENSARTECH","GRSE",
    # High Volume — Emerging
    "NETWEB","MEESHO","DELHIVERY","LATENTVIEW","DEVYANI",
    "CAMPUS","MPHASIS","MINDTREE","ROUTE","REDINGTON",
    "SEQUENT","SPARC","STARHEALTH","SUMICHEM","SUVEN",
    "TEAMLEASE","TCNSBRANDS","TVTODAY","VAIBHAVGBL","VSTIND",
    "WABCOINDIA","XPROINDIA","OLECTRA","POWMECH","PRAJIND",
    "PRINCEPIPE","RAINBOW","RAJESHEXPO","INDIACEM","CHAMBLFERT",
    "ELGIEQUIP","ENDURANCE","ENGINERSIN","FINEORG","FLUOROCHEM",
    "FORCEMOT","GSPL","HONAUT","LINDEINDIA","MIDHANI",
    "NMDC","PBFINTECH","RVNL","IRFC","HUDCO",
    "SJVN","NTPCGREEN","GPPL","GMDCLTD","EIHOTEL",
]

if __name__ == "__main__":
    print(f"Scanning {len(SYMBOLS)} stocks...\n")
    results = run_screener(SYMBOLS)
    print("\n=== ENTRY SIGNALS TODAY ===")
    if results.empty:
        print("No signals today.")
    else:
        cols = ["symbol","cmp","sma200","dist200_pct",
                "rsi","vol_ratio","stop_loss","target","risk_reward"]
        print(results[cols].to_string(index=False))
    os.makedirs("output", exist_ok=True)
    results.to_csv("output/signals_today.csv", index=False)
    print("\nSaved → output/signals_today.csv")
